/**
 * Generated by `npm run db:types` from supabase/migrations.
 *
 * Do not edit by hand: regenerate after changing a migration, so the
 * types can never drift from the schema they describe.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin: {
        Row: {
          admin_id: string
          user_id: string
          admin_first_name: string
          admin_last_name: string
          admin_created_at: string
        }
        Insert: {
          admin_id?: string
          user_id: string
          admin_first_name: string
          admin_last_name: string
          admin_created_at?: string
        }
        Update: {
          admin_id?: string
          user_id?: string
          admin_first_name?: string
          admin_last_name?: string
          admin_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'admin_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      announcement: {
        Row: {
          announcement_id: string
          admin_id: string
          announcement_title: string
          announcement_content: string
          announcement_published_at: string | null
          announcement_created_at: string
        }
        Insert: {
          announcement_id?: string
          admin_id: string
          announcement_title: string
          announcement_content: string
          announcement_published_at?: string | null
          announcement_created_at?: string
        }
        Update: {
          announcement_id?: string
          admin_id?: string
          announcement_title?: string
          announcement_content?: string
          announcement_published_at?: string | null
          announcement_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'announcement_admin_id_fkey'
            columns: ['admin_id']
            isOneToOne: false
            referencedRelation: 'admin'
            referencedColumns: ['admin_id']
          },
        ]
      }
      appointment: {
        Row: {
          appointment_id: string
          pat_id: string
          doc_id: string
          appointment_date: string
          appointment_status: Database['public']['Enums']['appointment_status']
          appointment_created_at: string
        }
        Insert: {
          appointment_id?: string
          pat_id: string
          doc_id: string
          appointment_date: string
          appointment_status?: Database['public']['Enums']['appointment_status']
          appointment_created_at?: string
        }
        Update: {
          appointment_id?: string
          pat_id?: string
          doc_id?: string
          appointment_date?: string
          appointment_status?: Database['public']['Enums']['appointment_status']
          appointment_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'appointment_doc_id_fkey'
            columns: ['doc_id']
            isOneToOne: false
            referencedRelation: 'doctor'
            referencedColumns: ['doc_id']
          },
          {
            foreignKeyName: 'appointment_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      audit_log: {
        Row: {
          audit_log_id: string
          user_id: string | null
          audit_log_action: string
          audit_log_entity: string
          audit_log_entity_id: string | null
          audit_log_timestamp: string
          audit_log_details: Json | null
        }
        Insert: {
          audit_log_id?: string
          user_id?: string | null
          audit_log_action: string
          audit_log_entity: string
          audit_log_entity_id?: string | null
          audit_log_timestamp?: string
          audit_log_details?: Json | null
        }
        Update: {
          audit_log_id?: string
          user_id?: string | null
          audit_log_action?: string
          audit_log_entity?: string
          audit_log_entity_id?: string | null
          audit_log_timestamp?: string
          audit_log_details?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: 'audit_log_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      chat_message: {
        Row: {
          chat_message_id: string
          chat_session_id: string
          chat_message_role: string
          chat_message_content: string
          chat_message_created_at: string
        }
        Insert: {
          chat_message_id?: string
          chat_session_id: string
          chat_message_role: string
          chat_message_content: string
          chat_message_created_at?: string
        }
        Update: {
          chat_message_id?: string
          chat_session_id?: string
          chat_message_role?: string
          chat_message_content?: string
          chat_message_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'chat_message_chat_session_id_fkey'
            columns: ['chat_session_id']
            isOneToOne: false
            referencedRelation: 'chat_session'
            referencedColumns: ['chat_session_id']
          },
        ]
      }
      chat_session: {
        Row: {
          chat_session_id: string
          pat_id: string
          chat_session_external_ref: string | null
          chat_session_started_at: string
          chat_session_ended_at: string | null
          chat_session_has_critical_flag: boolean
          chat_session_summary: string | null
        }
        Insert: {
          chat_session_id?: string
          pat_id: string
          chat_session_external_ref?: string | null
          chat_session_started_at?: string
          chat_session_ended_at?: string | null
          chat_session_has_critical_flag?: boolean
          chat_session_summary?: string | null
        }
        Update: {
          chat_session_id?: string
          pat_id?: string
          chat_session_external_ref?: string | null
          chat_session_started_at?: string
          chat_session_ended_at?: string | null
          chat_session_has_critical_flag?: boolean
          chat_session_summary?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'chat_session_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      doctor: {
        Row: {
          doc_id: string
          user_id: string
          doc_first_name: string
          doc_last_name: string
          doc_specialization: string | null
          doc_license_no: string
          doc_contact_no: string | null
          doc_is_active: boolean
          doc_created_at: string
        }
        Insert: {
          doc_id?: string
          user_id: string
          doc_first_name: string
          doc_last_name: string
          doc_specialization?: string | null
          doc_license_no: string
          doc_contact_no?: string | null
          doc_is_active?: boolean
          doc_created_at?: string
        }
        Update: {
          doc_id?: string
          user_id?: string
          doc_first_name?: string
          doc_last_name?: string
          doc_specialization?: string | null
          doc_license_no?: string
          doc_contact_no?: string | null
          doc_is_active?: boolean
          doc_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'doctor_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      doctor_note: {
        Row: {
          doctor_note_id: string
          pat_id: string
          doc_id: string
          doctor_note_text: string
          doctor_note_created_at: string
        }
        Insert: {
          doctor_note_id?: string
          pat_id: string
          doc_id: string
          doctor_note_text: string
          doctor_note_created_at?: string
        }
        Update: {
          doctor_note_id?: string
          pat_id?: string
          doc_id?: string
          doctor_note_text?: string
          doctor_note_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'doctor_note_doc_id_fkey'
            columns: ['doc_id']
            isOneToOne: false
            referencedRelation: 'doctor'
            referencedColumns: ['doc_id']
          },
          {
            foreignKeyName: 'doctor_note_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      medication_log: {
        Row: {
          medication_log_id: string
          medication_schedule_id: string
          medication_log_scheduled_at: string
          medication_log_taken_at: string | null
          medication_log_status: Database['public']['Enums']['medication_log_status']
          medication_log_follow_up_sent_at: string | null
        }
        Insert: {
          medication_log_id?: string
          medication_schedule_id: string
          medication_log_scheduled_at: string
          medication_log_taken_at?: string | null
          medication_log_status?: Database['public']['Enums']['medication_log_status']
          medication_log_follow_up_sent_at?: string | null
        }
        Update: {
          medication_log_id?: string
          medication_schedule_id?: string
          medication_log_scheduled_at?: string
          medication_log_taken_at?: string | null
          medication_log_status?: Database['public']['Enums']['medication_log_status']
          medication_log_follow_up_sent_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'medication_log_medication_schedule_id_fkey'
            columns: ['medication_schedule_id']
            isOneToOne: false
            referencedRelation: 'medication_schedule'
            referencedColumns: ['medication_schedule_id']
          },
        ]
      }
      medication_schedule: {
        Row: {
          medication_schedule_id: string
          prescription_id: string
          medication_schedule_name: string
          medication_schedule_dosage: string
          medication_schedule_frequency: number
          medication_schedule_times: string[]
          medication_schedule_start_date: string
          medication_schedule_end_date: string | null
          medication_schedule_created_at: string
        }
        Insert: {
          medication_schedule_id?: string
          prescription_id: string
          medication_schedule_name: string
          medication_schedule_dosage: string
          medication_schedule_frequency: number
          medication_schedule_times: string[]
          medication_schedule_start_date?: string
          medication_schedule_end_date?: string | null
          medication_schedule_created_at?: string
        }
        Update: {
          medication_schedule_id?: string
          prescription_id?: string
          medication_schedule_name?: string
          medication_schedule_dosage?: string
          medication_schedule_frequency?: number
          medication_schedule_times?: string[]
          medication_schedule_start_date?: string
          medication_schedule_end_date?: string | null
          medication_schedule_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'medication_schedule_prescription_id_fkey'
            columns: ['prescription_id']
            isOneToOne: false
            referencedRelation: 'prescription'
            referencedColumns: ['prescription_id']
          },
        ]
      }
      notification: {
        Row: {
          notification_id: string
          user_id: string
          chat_session_id: string | null
          notification_type: Database['public']['Enums']['notification_type']
          notification_message: string
          notification_is_read: boolean
          notification_created_at: string
        }
        Insert: {
          notification_id?: string
          user_id: string
          chat_session_id?: string | null
          notification_type: Database['public']['Enums']['notification_type']
          notification_message: string
          notification_is_read?: boolean
          notification_created_at?: string
        }
        Update: {
          notification_id?: string
          user_id?: string
          chat_session_id?: string | null
          notification_type?: Database['public']['Enums']['notification_type']
          notification_message?: string
          notification_is_read?: boolean
          notification_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notification_chat_session_id_fkey'
            columns: ['chat_session_id']
            isOneToOne: false
            referencedRelation: 'chat_session'
            referencedColumns: ['chat_session_id']
          },
          {
            foreignKeyName: 'notification_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      patient: {
        Row: {
          pat_id: string
          user_id: string
          doc_id: string
          pat_first_name: string
          pat_last_name: string
          pat_birth_date: string | null
          pat_gender: string | null
          pat_contact_no: string | null
          pat_address: string | null
          pat_consent_at: string | null
          pat_created_at: string
          pat_status: Database['public']['Enums']['patient_status']
          pat_reminder_preferred_time: string | null
          pat_reminder_is_enabled: boolean
        }
        Insert: {
          pat_id?: string
          user_id: string
          doc_id: string
          pat_first_name: string
          pat_last_name: string
          pat_birth_date?: string | null
          pat_gender?: string | null
          pat_contact_no?: string | null
          pat_address?: string | null
          pat_consent_at?: string | null
          pat_created_at?: string
          pat_status?: Database['public']['Enums']['patient_status']
          pat_reminder_preferred_time?: string | null
          pat_reminder_is_enabled?: boolean
        }
        Update: {
          pat_id?: string
          user_id?: string
          doc_id?: string
          pat_first_name?: string
          pat_last_name?: string
          pat_birth_date?: string | null
          pat_gender?: string | null
          pat_contact_no?: string | null
          pat_address?: string | null
          pat_consent_at?: string | null
          pat_created_at?: string
          pat_status?: Database['public']['Enums']['patient_status']
          pat_reminder_preferred_time?: string | null
          pat_reminder_is_enabled?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'patient_doc_id_fkey'
            columns: ['doc_id']
            isOneToOne: false
            referencedRelation: 'doctor'
            referencedColumns: ['doc_id']
          },
          {
            foreignKeyName: 'patient_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      prescription: {
        Row: {
          prescription_id: string
          pat_id: string
          doc_id: string
          prescription_issued_date: string
          prescription_notes: string | null
          prescription_created_at: string
        }
        Insert: {
          prescription_id?: string
          pat_id: string
          doc_id: string
          prescription_issued_date?: string
          prescription_notes?: string | null
          prescription_created_at?: string
        }
        Update: {
          prescription_id?: string
          pat_id?: string
          doc_id?: string
          prescription_issued_date?: string
          prescription_notes?: string | null
          prescription_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'prescription_doc_id_fkey'
            columns: ['doc_id']
            isOneToOne: false
            referencedRelation: 'doctor'
            referencedColumns: ['doc_id']
          },
          {
            foreignKeyName: 'prescription_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      recovery_log: {
        Row: {
          recovery_log_id: string
          pat_id: string
          recovery_log_date: string
          recovery_log_notes: string | null
          recovery_log_mood_rating: number | null
          recovery_log_created_at: string
        }
        Insert: {
          recovery_log_id?: string
          pat_id: string
          recovery_log_date?: string
          recovery_log_notes?: string | null
          recovery_log_mood_rating?: number | null
          recovery_log_created_at?: string
        }
        Update: {
          recovery_log_id?: string
          pat_id?: string
          recovery_log_date?: string
          recovery_log_notes?: string | null
          recovery_log_mood_rating?: number | null
          recovery_log_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'recovery_log_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      report: {
        Row: {
          report_id: string
          pat_id: string | null
          user_id: string
          report_type: Database['public']['Enums']['report_type']
          report_generated_at: string
          report_file_path: string | null
        }
        Insert: {
          report_id?: string
          pat_id?: string | null
          user_id: string
          report_type: Database['public']['Enums']['report_type']
          report_generated_at?: string
          report_file_path?: string | null
        }
        Update: {
          report_id?: string
          pat_id?: string | null
          user_id?: string
          report_type?: Database['public']['Enums']['report_type']
          report_generated_at?: string
          report_file_path?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'report_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
          {
            foreignKeyName: 'report_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      reschedule_request: {
        Row: {
          reschedule_request_id: string
          appointment_id: string
          user_id: string
          reschedule_request_date: string
          reschedule_request_reason: string | null
          reschedule_request_status: Database['public']['Enums']['reschedule_request_status']
          reschedule_request_responded_at: string | null
          reschedule_request_created_at: string
        }
        Insert: {
          reschedule_request_id?: string
          appointment_id: string
          user_id: string
          reschedule_request_date: string
          reschedule_request_reason?: string | null
          reschedule_request_status?: Database['public']['Enums']['reschedule_request_status']
          reschedule_request_responded_at?: string | null
          reschedule_request_created_at?: string
        }
        Update: {
          reschedule_request_id?: string
          appointment_id?: string
          user_id?: string
          reschedule_request_date?: string
          reschedule_request_reason?: string | null
          reschedule_request_status?: Database['public']['Enums']['reschedule_request_status']
          reschedule_request_responded_at?: string | null
          reschedule_request_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'reschedule_request_appointment_id_fkey'
            columns: ['appointment_id']
            isOneToOne: true
            referencedRelation: 'appointment'
            referencedColumns: ['appointment_id']
          },
          {
            foreignKeyName: 'reschedule_request_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'user_account'
            referencedColumns: ['user_id']
          },
        ]
      }
      system_setting: {
        Row: {
          system_setting_id: string
          admin_id: string | null
          system_setting_key: string
          system_setting_value: string
          system_setting_updated_at: string
        }
        Insert: {
          system_setting_id?: string
          admin_id?: string | null
          system_setting_key: string
          system_setting_value: string
          system_setting_updated_at?: string
        }
        Update: {
          system_setting_id?: string
          admin_id?: string | null
          system_setting_key?: string
          system_setting_value?: string
          system_setting_updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'system_setting_admin_id_fkey'
            columns: ['admin_id']
            isOneToOne: false
            referencedRelation: 'admin'
            referencedColumns: ['admin_id']
          },
        ]
      }
      treatment_goal: {
        Row: {
          treatment_goal_id: string
          treatment_plan_id: string
          treatment_goal_description: string
          treatment_goal_target_date: string | null
          treatment_goal_status: Database['public']['Enums']['treatment_goal_status']
          treatment_goal_created_at: string
        }
        Insert: {
          treatment_goal_id?: string
          treatment_plan_id: string
          treatment_goal_description: string
          treatment_goal_target_date?: string | null
          treatment_goal_status?: Database['public']['Enums']['treatment_goal_status']
          treatment_goal_created_at?: string
        }
        Update: {
          treatment_goal_id?: string
          treatment_plan_id?: string
          treatment_goal_description?: string
          treatment_goal_target_date?: string | null
          treatment_goal_status?: Database['public']['Enums']['treatment_goal_status']
          treatment_goal_created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'treatment_goal_treatment_plan_id_fkey'
            columns: ['treatment_plan_id']
            isOneToOne: false
            referencedRelation: 'treatment_plan'
            referencedColumns: ['treatment_plan_id']
          },
        ]
      }
      treatment_plan: {
        Row: {
          treatment_plan_id: string
          pat_id: string
          doc_id: string
          treatment_plan_title: string
          treatment_plan_description: string | null
          treatment_plan_start_date: string
          treatment_plan_end_date: string | null
          treatment_plan_status: Database['public']['Enums']['treatment_plan_status']
          treatment_plan_created_at: string
          treatment_plan_updated_at: string
        }
        Insert: {
          treatment_plan_id?: string
          pat_id: string
          doc_id: string
          treatment_plan_title: string
          treatment_plan_description?: string | null
          treatment_plan_start_date?: string
          treatment_plan_end_date?: string | null
          treatment_plan_status?: Database['public']['Enums']['treatment_plan_status']
          treatment_plan_created_at?: string
          treatment_plan_updated_at?: string
        }
        Update: {
          treatment_plan_id?: string
          pat_id?: string
          doc_id?: string
          treatment_plan_title?: string
          treatment_plan_description?: string | null
          treatment_plan_start_date?: string
          treatment_plan_end_date?: string | null
          treatment_plan_status?: Database['public']['Enums']['treatment_plan_status']
          treatment_plan_created_at?: string
          treatment_plan_updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'treatment_plan_doc_id_fkey'
            columns: ['doc_id']
            isOneToOne: false
            referencedRelation: 'doctor'
            referencedColumns: ['doc_id']
          },
          {
            foreignKeyName: 'treatment_plan_pat_id_fkey'
            columns: ['pat_id']
            isOneToOne: false
            referencedRelation: 'patient'
            referencedColumns: ['pat_id']
          },
        ]
      }
      user_account: {
        Row: {
          user_id: string
          user_email: string
          user_role: Database['public']['Enums']['user_role']
          user_created_at: string
          user_updated_at: string
        }
        Insert: {
          user_id: string
          user_email: string
          user_role: Database['public']['Enums']['user_role']
          user_created_at?: string
          user_updated_at?: string
        }
        Update: {
          user_id?: string
          user_email?: string
          user_role?: Database['public']['Enums']['user_role']
          user_created_at?: string
          user_updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'user_account_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      admin_dashboard_stats: {
        Args: Record<PropertyKey, never>
        Returns: Json
      }
      admin_chatbot_usage: {
        Args: { window_days?: number }
        Returns: Json
      }
    }
    Enums: {
      appointment_status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show'
      medication_log_status: 'pending' | 'taken' | 'missed' | 'skipped'
      notification_type: 'appointment' | 'medication' | 'treatment' | 'chat_critical' | 'announcement' | 'general'
      patient_status: 'active' | 'inactive' | 'discharged'
      report_type: 'patient_recovery' | 'system_wide'
      reschedule_request_status: 'pending' | 'approved' | 'declined'
      treatment_goal_status: 'pending' | 'in_progress' | 'achieved' | 'missed'
      treatment_plan_status: 'draft' | 'active' | 'completed' | 'cancelled'
      user_role: 'patient' | 'doctor' | 'admin'
    }
    CompositeTypes: { [_ in never]: never }
  }
}

/** Convenience alias: the Row shape of a public table. */
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

/** Convenience alias: the Insert shape of a public table. */
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

/** Convenience alias: the Update shape of a public table. */
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

/** Convenience alias: a public enum union. */
export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
