-- ===========================================================================
-- RecoverEase — 05. Operations
-- ===========================================================================
-- ERD entities: report, auditLog, systemSetting.
-- ===========================================================================

-- Module 9 defines exactly two kinds of report: a per-patient recovery report
-- generated by a doctor (9.1) and a system-wide report generated by an
-- administrator (9.3).
create type public.report_type as enum ('patient_recovery', 'system_wide');

-- ---------------------------------------------------------------------------
-- report
-- ---------------------------------------------------------------------------
-- `pat_id` is NULLABLE, which the ERD does not say. A system-wide report
-- (module 9.3) has no single subject patient, so requiring one would make
-- that module impossible to implement. The CHECK constraint keeps the two
-- shapes honest: a recovery report must name a patient, a system-wide report
-- must not.

create table public.report (
  report_id           uuid primary key default gen_random_uuid(),
  pat_id              uuid
                        references public.patient (pat_id)
                        on delete cascade,
  -- Who generated it. ON DELETE RESTRICT: a report must remain attributable.
  user_id             uuid not null
                        references public.user_account (user_id)
                        on delete restrict,
  report_type         public.report_type not null,
  report_generated_at timestamptz not null default now(),
  -- Object path in Supabase Storage. NULL while generation is in flight.
  report_file_path    text,

  constraint report_subject_matches_type
    check (
      (report_type = 'patient_recovery' and pat_id is not null)
      or (report_type = 'system_wide' and pat_id is null)
    )
);

create index report_generated_by_idx
  on public.report (user_id, report_generated_at desc);

create index report_patient_idx
  on public.report (pat_id, report_generated_at desc)
  where pat_id is not null;

comment on table public.report is
  'ERD: report. pat_id is nullable because a system-wide report (module 9.3) '
  'has no subject patient; the CHECK constraint enforces which shape goes '
  'with which type.';

-- ---------------------------------------------------------------------------
-- auditLog
-- ---------------------------------------------------------------------------
-- Append-only. Migration 05 grants no UPDATE or DELETE policy to anyone, so
-- the history cannot be rewritten through the API even by an administrator.
--
-- `user_id` is ON DELETE SET NULL rather than CASCADE: deleting an account
-- must not erase the record of what that account did. This is the single most
-- important referential decision in the file.
--
-- REFINEMENT: `auditLogDetails` is `text` in the ERD, stored here as `jsonb`.
-- Module 13.2 is "Filter / Search Audit Logs", which is a structured query
-- over structured data; jsonb makes that indexable instead of a substring
-- scan over prose.

create table public.audit_log (
  audit_log_id        uuid primary key default gen_random_uuid(),
  user_id             uuid
                        references public.user_account (user_id)
                        on delete set null,
  audit_log_action    text not null,
  audit_log_entity    text not null,
  audit_log_entity_id uuid,
  audit_log_timestamp timestamptz not null default now(),
  audit_log_details   jsonb,

  constraint audit_log_action_not_blank check (btrim(audit_log_action) <> ''),
  constraint audit_log_entity_not_blank check (btrim(audit_log_entity) <> '')
);

-- Module 13.2 filters by actor, by entity, and by time.
create index audit_log_timestamp_idx
  on public.audit_log (audit_log_timestamp desc);

create index audit_log_user_idx
  on public.audit_log (user_id, audit_log_timestamp desc);

create index audit_log_entity_idx
  on public.audit_log (audit_log_entity, audit_log_entity_id);

comment on table public.audit_log is
  'ERD: auditLog. Append-only: no UPDATE or DELETE policy exists for any '
  'role. user_id is SET NULL on account deletion so history survives.';

-- ---------------------------------------------------------------------------
-- systemSetting
-- ---------------------------------------------------------------------------
-- Key/value configuration owned by administrators (module 14.1), including
-- the chatbot system prompt and response guidelines (module 8.7).
--
-- `admin_id` records the last administrator to change the value and is
-- ON DELETE SET NULL so removing an admin account never destroys settings.

create table public.system_setting (
  system_setting_id         uuid primary key default gen_random_uuid(),
  admin_id                  uuid
                              references public.admin (admin_id)
                              on delete set null,
  system_setting_key        text not null,
  system_setting_value      text not null,
  system_setting_updated_at timestamptz not null default now(),

  constraint system_setting_key_not_blank
    check (btrim(system_setting_key) <> '')
);

-- A settings table without a unique key is a bug waiting to happen: two rows
-- for the same key means the effective value depends on row order.
create unique index system_setting_key_unique
  on public.system_setting (system_setting_key);

create trigger system_setting_set_updated_at
  before update on public.system_setting
  for each row
  execute function public.set_updated_at('system_setting_updated_at');

comment on table public.system_setting is
  'ERD: systemSetting. Administrator-owned key/value configuration '
  '(module 14.1), including the chatbot system prompt (module 8.7).';
